### ISSUE TITLE
Paperpile access information page missing information on who to contact to get password

### ISSUE THREAD

**Issue by mathieuboudreau** [neuropoly/neuropoly-internal-docs#12]
Under "Publishing articles --> references", it indicates a username to use but not who in the lab we should contact to get the password to access our lab paperpile.

**Comment by jcohenadad** [comment]
@mathieuboudreau I don't find "Publishing articles --> references". Are you referring to [this section](https://app.gitbook.com/@neuropoly/s/neuropoly-lab/writing-articles#install-paperpile)? If so, it is true that the "neuropoly google account" might be unclear (although we mention it in the onboarding)

**Comment by mathieuboudreau** [comment]
I wasn't sure how much details to put in here since this repo isn't private, so I only gave the final section that arrived to. Here are the steps that I followed to arrive to that section.

* Go to https://app.gitbook.com/@neuropoly/s/neuropoly-lab/onboarding
* On the left panel, click "Bibliography & Learning"
* Then click "Bibliography" in the subsection of the left panel that just expanded.
* Click "Paperpile" in the left panel that just expanded.
* Then in the main panel, click the link on the word "here" where it says "Please follow the instructions listed here to access Paperpile."
* The page that now opened should now be in the section I referenced in my initial issue here.

**Comment by jcohenadad** [comment]
The link was pointing to a draft version of the gitbook 😞 .
i've now updated the link.
thank you for finding this issue @mathieuboudreau

**Comment by jcohenadad** [comment]
please let me know if it resolves the issue on your end

**Comment by mathieuboudreau** [comment]
Great, thanks!

The instructions say "Connect to Paperpile website with the NeuroPoly Google account", however I don't see instructions on how to get login information under [Accounts](https://intranet.neuro.polymtl.ca/onboarding/accounts) in OnBoarding. Did I miss where that information (or who to contact) would be kept? (sorry, since my old laptop was stolen I have to find all my old login/passwords that were saved in my Safari keychain to use with my new laptop)

**Comment by mathieuboudreau** [comment]
Oh I guess maybe it would fall under the introduction instructions "To request an account for most of these services, ask on Slack #welcome and tag @alexfoias. He will either create one or direct you to where to get the account created."? I just glanced at the "Accounts Overview" and couldn't find that one listed. I'll contact Alex, thanks!
