### ISSUE TITLE
Update intranet to reflect upstream VPN changes

### ISSUE THREAD

**Issue by nullnik-0** [neuropoly/neuropoly-internal-docs#133]
## Background

On Friday September 13th at 17h30 upstream IT sent and email to announce that, due to security concerns, they would be disabling the `PolySSL` `VPN` group for employees. This connection was disabled at 18h that same day (half an hour later.) Employees were told to instead use the `PolyQuartz` `VPN`, which uses an authentication flow that is not supported by `openconnect`.

Our current workflow at the lab encourages users to use `openconnect` because `anyconnect` is a proprietary software that requires root access to install and has many [potentially very invasive](https://www.cisco.com/c/en/us/td/docs/security/vpn_client/anyconnect/anyconnect410/administration/guide/b-anyconnect-admin-guide-4-10/nvm.html) endpoint monitoring and telemetry capabilities.

For those affected by the upstream change (as of writing, the full scope of this change is not clear), it means that we are now required use the cisco `anyconnect` client instead of `openconnect`

None of this is documented by our [existing VPN docs](https://intranet.neuro.polymtl.ca/computing-resources/neuropoly/README.html#vpn). These docs need to be updated to relfect the new VPN requirements and how it will affect different users. However first we need to understand exactly who will be affected and how, and look at possible solutions that address user concerns about privacy. 

## Next steps

- [x] Confirm whether or not upstream might be willing to be flexible about this. @jcohenadad  has already contacted upstream about this.
- [x] Determine who is affected and who will be affected in the future.
  - Right now we know for sure that employees (and people classed as employees for VPN purposes) are affected.
  - Anecdotally, it seems that students are not affected and this is reflected in the [official Polytechique VPN docs](https://www.polymtl.ca/si/acces-securise-rvp-ou-vpn)
  - However, it is plausible that upstream intends to roll out these changes for students at some point in the future. We should try to confirm this if possible, so that we can have a better understanding of the potential scope of effects on the lab.
- [x] Investigate whether it might be possible to reverse engineer the `anyconnect` auth flow and get it working with `openconnect`. (See this [info](https://www.infradead.org/openconnect/contribute.html) and [these](https://github.com/dlenski/openconnect/issues/143) [discussions](https://superuser.com/questions/284709/how-to-allow-local-lan-access-while-connected-to-cisco-vpn/1753172#1753172) and [projects](https://github.com/vlaci/openconnect-sso) for more context...
- [ ] Document new VPN workflows for different use cases and types of end users on the intranet.

## Known issues and solutions

- I was concerned about the privacy implications of being forced to install `anyconnect` on my personal device (which is also my work device). I got `anyconnect` working properly in a `vm`, and tested with both `NAT mode` and `bridge mode`. This clearly not an ideal set up for many users.
- @mathieuboudreau  had already installed `anyconnect` on a `macos` and found he needed to do the following to get `anyconnect` working with the `PolyQuartz` profile:
    1. Uninstall `cisco anyconnect`
    2. Open a terminal and run `sudo rm -rf /opt/cisco`
    3. Reinstall `cisco anyconnect`
    4. (annoyingly) add `anyconnect` to login items
    5. Type `ssl.vpn.polymtl.ca` in the `anyconnect` prompt
    6. Select `PolyQuartz` option
- @namgo is part of the `PolyInvites` group. This seems to have also been shut down by upstream, despite the fact that it was not mentioned in the original communiqué. As a contractor Nathan has not been included in the Okta transition and thus is not able to use the Okta-based auth flow under any circumstances. There is **no know solution** to this as of writing and **Nathan has been functionally blocked from job-critical access to our infrastructure**.
- It looks like `interns` are also affected by a similar issue as Nathan, and currently don't have a viable VPN option. Their existing VPN access has been revoked, but since they are not full employees, they have not been included in the `Okta` transition and thus cannot use `PolyQuartz`.

**Comment by namgo** [comment]
> you should notify Julien and upstream

I let Julien know, and I'm working through debugging what I can first. I might still have a way to sign up for Okta... or I might have been forgotten in that mix, we'll see.

**Comment by jcohenadad** [comment]
@namgo @nullnik-0 can you please document the suggestions that JS sent us after talking with Yves Simard? Thanks!

**Comment by jcohenadad** [comment]
> I've drafted a message to upstream explaining this and asking for clarification. I believe @namgo was going to send it on my behalf tomorrow, but if you would like to forward please do!

All good, I let you or Nathan send it. Just wanted to make sure we follow up with them. Thanks!

**Comment by namgo** [comment]
Sent!

**Comment by namgo** [comment]
Very well written! One thing I'd add is that you can use Linux Containers (lxc/lxd/incus and probably docker with added steps) which skips the need for hypervisor configuration. That's what I have been doing, but I had a bit of trouble with this on my end due to running obscure non-systemd distros primarily (Void and Alpine), where anyconnect requires systemd hooks and Void doesn't play nice with systemd containers like the ubuntu base image.

**Comment by SomeoneInParticular** [comment]
Regarding @nullnik-0 remark, I have a working script up and ready (though only tested w/ Selenium's Firefox driver, and only on my Linux-like system). 

To that ends does anyone have preference on whether the script should be hosted as a personal repository or on NeuroPoly (so it can be more easily maintained if/when I leave the lab)?

**Comment by mguaypaq** [comment]
I think it's fine to host it in a personal repository, since it's very unofficial. It's unlikely that anyone else will maintain the script, but if they do it's easy to fork the repository at that point.

**Comment by SomeoneInParticular** [comment]
The code has been uploaded and is available [here](https://github.com/SomeoneInParticular/AutoPolyVPN/tree/master). Feel free to test and push any feature requests/issues!
